-- 为已有表/字段补充中文注释，不改变类型与约束。

ALTER TABLE sys_user
    COMMENT = '系统用户',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE workspace
    COMMENT = '工作空间',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '工作空间ID',
    MODIFY COLUMN tenant_id BIGINT UNSIGNED NOT NULL COMMENT '所属租户ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '工作空间名称',
    MODIFY COLUMN slug VARCHAR(128) NOT NULL COMMENT 'URL 标识',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '描述',
    MODIFY COLUMN avatar_url VARCHAR(500) NULL COMMENT '头像',
    MODIFY COLUMN owner_id BIGINT UNSIGNED NOT NULL COMMENT '所有者用户ID',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE workspace_member
    COMMENT = '工作空间成员',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_id BIGINT UNSIGNED NULL COMMENT '角色ID',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0停用',
    MODIFY COLUMN joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE sys_role
    COMMENT = '角色',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NULL COMMENT '工作空间ID，空表示平台内置角色',
    MODIFY COLUMN role_code VARCHAR(64) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN role_name VARCHAR(64) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '描述',
    MODIFY COLUMN built_in TINYINT NOT NULL DEFAULT 0 COMMENT '是否内置：1是 0否',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE sys_permission
    COMMENT = '权限点',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
    MODIFY COLUMN permission_code VARCHAR(128) NOT NULL COMMENT '权限编码',
    MODIFY COLUMN permission_name VARCHAR(128) NOT NULL COMMENT '权限名称',
    MODIFY COLUMN resource_type VARCHAR(64) NULL COMMENT '资源类型',
    MODIFY COLUMN action VARCHAR(64) NULL COMMENT '操作类型',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '描述',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sys_role_permission
    COMMENT = '角色权限关系',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN role_id BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    MODIFY COLUMN permission_id BIGINT UNSIGNED NOT NULL COMMENT '权限ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE model_provider
    COMMENT = '工作空间模型服务商',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN provider_code VARCHAR(64) NOT NULL COMMENT '服务商编码',
    MODIFY COLUMN provider_name VARCHAR(128) NOT NULL COMMENT '服务商名称',
    MODIFY COLUMN provider_type VARCHAR(64) NOT NULL COMMENT '服务商类型',
    MODIFY COLUMN base_url VARCHAR(500) NULL COMMENT '接口地址',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN config_json JSON NULL COMMENT '扩展配置',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE model_definition
    COMMENT = '工作空间模型定义',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN provider_id BIGINT UNSIGNED NOT NULL COMMENT '服务商ID',
    MODIFY COLUMN model_code VARCHAR(128) NOT NULL COMMENT '模型编码',
    MODIFY COLUMN model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    MODIFY COLUMN model_type VARCHAR(32) NOT NULL DEFAULT 'CHAT' COMMENT '模型类型：CHAT/EMBEDDING 等',
    MODIFY COLUMN support_streaming TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持流式',
    MODIFY COLUMN support_tool_calling TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持工具调用',
    MODIFY COLUMN support_vision TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持视觉',
    MODIFY COLUMN context_window INT NULL COMMENT '上下文窗口大小',
    MODIFY COLUMN max_output_tokens INT NULL COMMENT '最大输出 Token',
    MODIFY COLUMN input_price DECIMAL(18,8) NULL COMMENT '输入单价',
    MODIFY COLUMN output_price DECIMAL(18,8) NULL COMMENT '输出单价',
    MODIFY COLUMN config_json JSON NULL COMMENT '扩展配置',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE model_credential
    COMMENT = '工作空间模型密钥',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN provider_id BIGINT UNSIGNED NOT NULL COMMENT '服务商ID',
    MODIFY COLUMN credential_name VARCHAR(128) NOT NULL COMMENT '密钥名称',
    MODIFY COLUMN encrypted_api_key TEXT NOT NULL COMMENT '加密后的 API Key',
    MODIFY COLUMN encrypted_secret TEXT NULL COMMENT '加密后的 Secret',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN last_used_at DATETIME NULL COMMENT '最近使用时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE agent
    COMMENT = '智能体',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '智能体ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '描述',
    MODIFY COLUMN avatar_url VARCHAR(500) NULL COMMENT '头像',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED 等',
    MODIFY COLUMN published_version_id BIGINT UNSIGNED NULL COMMENT '已发布版本ID',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE agent_version
    COMMENT = '智能体版本',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '版本ID',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN version_no INT NOT NULL COMMENT '版本号',
    MODIFY COLUMN version_name VARCHAR(128) NULL COMMENT '版本名称',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED 等',
    MODIFY COLUMN system_prompt LONGTEXT NULL COMMENT '系统提示词',
    MODIFY COLUMN model_id BIGINT UNSIGNED NULL COMMENT '工作空间模型ID',
    MODIFY COLUMN platform_model_id BIGINT UNSIGNED NULL COMMENT '平台模型ID',
    MODIFY COLUMN temperature DECIMAL(5,4) NULL COMMENT '采样温度',
    MODIFY COLUMN top_p DECIMAL(5,4) NULL COMMENT '核采样 top_p',
    MODIFY COLUMN max_tokens INT NULL COMMENT '最大生成 Token',
    MODIFY COLUMN stream_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否流式输出',
    MODIFY COLUMN memory_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用会话记忆',
    MODIFY COLUMN memory_window_size INT NOT NULL DEFAULT 20 COMMENT '会话记忆窗口条数',
    MODIFY COLUMN knowledge_enabled TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用知识库',
    MODIFY COLUMN tool_enabled TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用工具',
    MODIFY COLUMN config_json JSON NULL COMMENT '扩展配置',
    MODIFY COLUMN published_at DATETIME NULL COMMENT '发布时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE conversation
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '会话ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN agent_version_id BIGINT UNSIGNED NULL COMMENT '智能体版本ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    MODIFY COLUMN title VARCHAR(255) NULL COMMENT '会话标题',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/ARCHIVED 等',
    MODIFY COLUMN message_count INT NOT NULL DEFAULT 0 COMMENT '消息条数',
    MODIFY COLUMN last_message_at DATETIME NULL COMMENT '最后消息时间',
    MODIFY COLUMN metadata JSON NULL COMMENT '扩展元数据',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE message
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '消息ID',
    MODIFY COLUMN conversation_id BIGINT UNSIGNED NOT NULL COMMENT '会话ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN content LONGTEXT COMMENT '消息内容',
    MODIFY COLUMN content_type VARCHAR(32) NOT NULL DEFAULT 'TEXT' COMMENT '内容类型：TEXT 等',
    MODIFY COLUMN sequence_no INT NOT NULL COMMENT '会话内序号',
    MODIFY COLUMN token_count INT NULL COMMENT 'Token 数',
    MODIFY COLUMN model_id BIGINT UNSIGNED NULL COMMENT '调用模型ID',
    MODIFY COLUMN metadata JSON NULL COMMENT '扩展元数据',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE tenant
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '租户名称',
    MODIFY COLUMN slug VARCHAR(128) NOT NULL COMMENT 'URL 标识',
    MODIFY COLUMN contact_email VARCHAR(128) NULL COMMENT '联系邮箱',
    MODIFY COLUMN owner_id BIGINT UNSIGNED NULL COMMENT '所有者用户ID',
    MODIFY COLUMN plan_id BIGINT UNSIGNED NULL COMMENT '套餐ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE tenant_member
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_code VARCHAR(64) NOT NULL DEFAULT 'TENANT_ADMIN' COMMENT '租户角色编码',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0停用',
    MODIFY COLUMN joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE plan
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '套餐ID',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '套餐编码',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '套餐名称',
    MODIFY COLUMN description VARCHAR(512) NULL COMMENT '描述',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE tenant_usage
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tenant_id BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
    MODIFY COLUMN ai_calls INT NOT NULL DEFAULT 0 COMMENT '当月 AI 调用次数',
    MODIFY COLUMN tokens BIGINT NOT NULL DEFAULT 0 COMMENT '当月 Token 用量',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE platform_provider
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN provider_code VARCHAR(64) NOT NULL COMMENT '服务商编码',
    MODIFY COLUMN provider_name VARCHAR(128) NOT NULL COMMENT '服务商名称',
    MODIFY COLUMN provider_type VARCHAR(64) NOT NULL DEFAULT 'OPENAI_COMPATIBLE' COMMENT '服务商类型',
    MODIFY COLUMN base_url VARCHAR(500) NULL COMMENT '接口地址',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE platform_model
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '平台模型ID',
    MODIFY COLUMN provider_id BIGINT UNSIGNED NOT NULL COMMENT '服务商ID',
    MODIFY COLUMN model_code VARCHAR(128) NOT NULL COMMENT '模型编码',
    MODIFY COLUMN model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '描述',
    MODIFY COLUMN model_type VARCHAR(32) NOT NULL DEFAULT 'CHAT' COMMENT '模型类型',
    MODIFY COLUMN support_streaming TINYINT NOT NULL DEFAULT 1 COMMENT '是否支持流式',
    MODIFY COLUMN context_window INT NULL COMMENT '上下文窗口大小',
    MODIFY COLUMN max_output_tokens INT NULL COMMENT '最大输出 Token',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE platform_credential
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN provider_id BIGINT UNSIGNED NOT NULL COMMENT '服务商ID',
    MODIFY COLUMN credential_name VARCHAR(128) NOT NULL COMMENT '密钥名称',
    MODIFY COLUMN encrypted_api_key TEXT NOT NULL COMMENT '加密后的 API Key',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN last_used_at DATETIME NULL COMMENT '最近使用时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE agent_template
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '模板ID',
    MODIFY COLUMN template_code VARCHAR(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '模板名称',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '描述',
    MODIFY COLUMN avatar_url VARCHAR(500) NULL COMMENT '头像',
    MODIFY COLUMN category VARCHAR(64) NULL COMMENT '分类',
    MODIFY COLUMN system_prompt LONGTEXT NULL COMMENT '系统提示词',
    MODIFY COLUMN platform_model_id BIGINT UNSIGNED NULL COMMENT '平台模型ID',
    MODIFY COLUMN temperature DECIMAL(5,4) NULL COMMENT '采样温度',
    MODIFY COLUMN top_p DECIMAL(5,4) NULL COMMENT '核采样 top_p',
    MODIFY COLUMN max_tokens INT NULL COMMENT '最大生成 Token',
    MODIFY COLUMN stream_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否流式输出',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN install_count INT NOT NULL DEFAULT 0 COMMENT '安装次数',
    MODIFY COLUMN created_by BIGINT UNSIGNED NULL COMMENT '创建人用户ID',
    MODIFY COLUMN updated_by BIGINT UNSIGNED NULL COMMENT '更新人用户ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE user_preference
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_sidebar_pin
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN target_id BIGINT UNSIGNED NOT NULL COMMENT '固定对象ID',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE plugin_catalog
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '插件ID',
    MODIFY COLUMN plugin_code VARCHAR(64) NOT NULL COMMENT '插件编码',
    MODIFY COLUMN title VARCHAR(128) NOT NULL COMMENT '标题',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '描述',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'LISTED' COMMENT 'LISTED/ARCHIVED 等',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN install_count INT NOT NULL DEFAULT 0 COMMENT '安装次数',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE workspace_plugin_install
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN plugin_id BIGINT UNSIGNED NOT NULL COMMENT '插件ID',
    MODIFY COLUMN installed_by BIGINT UNSIGNED NOT NULL COMMENT '安装人用户ID',
    MODIFY COLUMN installed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '安装时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE system_config
    MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '配置键',
    MODIFY COLUMN config_value LONGTEXT NULL COMMENT '配置值',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '说明',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE plugin_category
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_workspace_selection
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE knowledge_base
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '知识库ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN description VARCHAR(512) DEFAULT NULL COMMENT '描述',
    MODIFY COLUMN icon VARCHAR(512) DEFAULT NULL COMMENT '图标',
    MODIFY COLUMN embedding_model_id BIGINT UNSIGNED DEFAULT NULL COMMENT '向量模型ID',
    MODIFY COLUMN rerank_model_id BIGINT UNSIGNED DEFAULT NULL COMMENT '重排序模型ID',
    MODIFY COLUMN chunk_config JSON DEFAULT NULL COMMENT '切片配置',
    MODIFY COLUMN retrieval_config JSON DEFAULT NULL COMMENT '检索配置',
    MODIFY COLUMN document_count INT NOT NULL DEFAULT 0 COMMENT '文档数量',
    MODIFY COLUMN chunk_count BIGINT NOT NULL DEFAULT 0 COMMENT '分块数量',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'READY' COMMENT '状态',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE knowledge_document
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文档ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN knowledge_base_id BIGINT UNSIGNED NOT NULL COMMENT '知识库ID',
    MODIFY COLUMN name VARCHAR(255) NOT NULL COMMENT '显示名称',
    MODIFY COLUMN file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    MODIFY COLUMN file_type VARCHAR(32) NOT NULL COMMENT '文件类型',
    MODIFY COLUMN mime_type VARCHAR(128) DEFAULT NULL COMMENT 'MIME 类型',
    MODIFY COLUMN file_size BIGINT DEFAULT NULL COMMENT '文件大小（字节）',
    MODIFY COLUMN storage_bucket VARCHAR(128) DEFAULT NULL COMMENT '对象存储桶',
    MODIFY COLUMN storage_key VARCHAR(1024) DEFAULT NULL COMMENT '对象存储键',
    MODIFY COLUMN md5 VARCHAR(64) DEFAULT NULL COMMENT '文件 MD5',
    MODIFY COLUMN page_count INT DEFAULT NULL COMMENT '页数',
    MODIFY COLUMN chunk_count INT NOT NULL DEFAULT 0 COMMENT '分块数量',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'UPLOADING' COMMENT '处理状态',
    MODIFY COLUMN error_message TEXT DEFAULT NULL COMMENT '失败原因',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE knowledge_chunk
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分块ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN knowledge_base_id BIGINT UNSIGNED NOT NULL COMMENT '知识库ID',
    MODIFY COLUMN document_id BIGINT UNSIGNED NOT NULL COMMENT '文档ID',
    MODIFY COLUMN chunk_index INT NOT NULL COMMENT '文档内分块序号',
    MODIFY COLUMN content LONGTEXT NOT NULL COMMENT '分块文本',
    MODIFY COLUMN token_count INT DEFAULT NULL COMMENT 'Token 数',
    MODIFY COLUMN page_number INT DEFAULT NULL COMMENT '来源页码',
    MODIFY COLUMN metadata JSON DEFAULT NULL COMMENT '扩展元数据',
    MODIFY COLUMN es_document_id VARCHAR(128) NOT NULL COMMENT 'Elasticsearch 文档ID',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'INDEXED' COMMENT '索引状态',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE tool
    COMMENT = '工具',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '工具ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN tool_key VARCHAR(128) NOT NULL COMMENT '工具唯一键',
    MODIFY COLUMN description VARCHAR(512) DEFAULT NULL COMMENT '描述',
    MODIFY COLUMN type VARCHAR(32) NOT NULL COMMENT '类型：HTTP/DATABASE/FUNCTION 等',
    MODIFY COLUMN input_schema JSON DEFAULT NULL COMMENT '输入参数 Schema',
    MODIFY COLUMN output_schema JSON DEFAULT NULL COMMENT '输出 Schema',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE tool_http_config
    COMMENT = 'HTTP 工具配置',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tool_id BIGINT UNSIGNED NOT NULL COMMENT '工具ID',
    MODIFY COLUMN method VARCHAR(16) NOT NULL COMMENT 'HTTP 方法',
    MODIFY COLUMN url VARCHAR(2048) NOT NULL COMMENT '请求地址',
    MODIFY COLUMN headers JSON DEFAULT NULL COMMENT '请求头',
    MODIFY COLUMN query_params JSON DEFAULT NULL COMMENT '查询参数',
    MODIFY COLUMN body_type VARCHAR(32) DEFAULT NULL COMMENT '请求体类型',
    MODIFY COLUMN body_template LONGTEXT DEFAULT NULL COMMENT '请求体模板',
    MODIFY COLUMN timeout_ms INT NOT NULL DEFAULT 10000 COMMENT '超时毫秒',
    MODIFY COLUMN allow_redirect TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许重定向',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间';

ALTER TABLE agent_knowledge
    COMMENT = '智能体知识库绑定',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN version_id BIGINT UNSIGNED NOT NULL COMMENT '智能体版本ID',
    MODIFY COLUMN knowledge_base_id BIGINT UNSIGNED NOT NULL COMMENT '知识库ID',
    MODIFY COLUMN top_k INT NOT NULL DEFAULT 5 COMMENT '召回条数',
    MODIFY COLUMN score_threshold DECIMAL(8,6) DEFAULT NULL COMMENT '分数阈值',
    MODIFY COLUMN retrieval_mode VARCHAR(32) NOT NULL DEFAULT 'HYBRID' COMMENT '检索模式：HYBRID/KEYWORD/VECTOR',
    MODIFY COLUMN rerank_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否重排序',
    MODIFY COLUMN citation_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否返回引用',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE agent_tool
    COMMENT = '智能体工具绑定',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN version_id BIGINT UNSIGNED NOT NULL COMMENT '智能体版本ID',
    MODIFY COLUMN tool_id BIGINT UNSIGNED NOT NULL COMMENT '工具ID',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN require_confirmation TINYINT NOT NULL DEFAULT 0 COMMENT '调用前是否需确认',
    MODIFY COLUMN config JSON DEFAULT NULL COMMENT '绑定配置',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE workflow
    COMMENT = '工作流',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '工作流ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN description VARCHAR(512) DEFAULT NULL COMMENT '描述',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED 等',
    MODIFY COLUMN draft_version_id BIGINT UNSIGNED DEFAULT NULL COMMENT '草稿版本ID',
    MODIFY COLUMN published_version_id BIGINT UNSIGNED DEFAULT NULL COMMENT '已发布版本ID',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE workflow_version
    COMMENT = '工作流版本',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '版本ID',
    MODIFY COLUMN workflow_id BIGINT UNSIGNED NOT NULL COMMENT '工作流ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN version_no INT NOT NULL COMMENT '版本号',
    MODIFY COLUMN definition JSON NOT NULL COMMENT '画布定义 JSON',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
    MODIFY COLUMN change_log VARCHAR(512) DEFAULT NULL COMMENT '变更说明',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE execution
    COMMENT = '智能体/工作流执行记录',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '执行ID',
    MODIFY COLUMN execution_no VARCHAR(64) NOT NULL COMMENT '执行编号',
    MODIFY COLUMN request_id VARCHAR(64) DEFAULT NULL COMMENT '请求追踪ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN execution_type VARCHAR(32) NOT NULL COMMENT '执行类型：AGENT/WORKFLOW 等',
    MODIFY COLUMN agent_id BIGINT UNSIGNED DEFAULT NULL COMMENT '智能体ID',
    MODIFY COLUMN agent_version_id BIGINT UNSIGNED DEFAULT NULL COMMENT '智能体版本ID',
    MODIFY COLUMN workflow_id BIGINT UNSIGNED DEFAULT NULL COMMENT '工作流ID',
    MODIFY COLUMN workflow_version_id BIGINT UNSIGNED DEFAULT NULL COMMENT '工作流版本ID',
    MODIFY COLUMN conversation_id BIGINT UNSIGNED DEFAULT NULL COMMENT '会话ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED DEFAULT NULL COMMENT '发起用户ID',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '执行状态',
    MODIFY COLUMN input_json JSON DEFAULT NULL COMMENT '输入',
    MODIFY COLUMN output_json JSON DEFAULT NULL COMMENT '输出',
    MODIFY COLUMN error_code VARCHAR(128) DEFAULT NULL COMMENT '错误码',
    MODIFY COLUMN error_message TEXT DEFAULT NULL COMMENT '错误信息',
    MODIFY COLUMN started_at DATETIME(3) DEFAULT NULL COMMENT '开始时间',
    MODIFY COLUMN finished_at DATETIME(3) DEFAULT NULL COMMENT '结束时间',
    MODIFY COLUMN duration_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    MODIFY COLUMN total_tokens INT DEFAULT NULL COMMENT '总 Token',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE trace
    COMMENT = '执行链路',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路ID',
    MODIFY COLUMN execution_id BIGINT UNSIGNED NOT NULL COMMENT '执行记录ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '链路名称',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '状态',
    MODIFY COLUMN start_time DATETIME(3) NOT NULL COMMENT '开始时间',
    MODIFY COLUMN end_time DATETIME(3) DEFAULT NULL COMMENT '结束时间',
    MODIFY COLUMN duration_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    MODIFY COLUMN metadata JSON DEFAULT NULL COMMENT '扩展元数据',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE trace_span
    COMMENT = '执行 Span',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN trace_id VARCHAR(64) NOT NULL COMMENT '链路ID',
    MODIFY COLUMN span_id VARCHAR(64) NOT NULL COMMENT 'Span ID',
    MODIFY COLUMN parent_span_id VARCHAR(64) DEFAULT NULL COMMENT '父 Span ID',
    MODIFY COLUMN span_type VARCHAR(32) NOT NULL COMMENT 'Span 类型',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '状态',
    MODIFY COLUMN input JSON DEFAULT NULL COMMENT '输入',
    MODIFY COLUMN output JSON DEFAULT NULL COMMENT '输出',
    MODIFY COLUMN model_id BIGINT UNSIGNED DEFAULT NULL COMMENT '模型ID',
    MODIFY COLUMN tool_id BIGINT UNSIGNED DEFAULT NULL COMMENT '工具ID',
    MODIFY COLUMN input_tokens INT DEFAULT NULL COMMENT '输入 Token',
    MODIFY COLUMN output_tokens INT DEFAULT NULL COMMENT '输出 Token',
    MODIFY COLUMN start_time DATETIME(3) NOT NULL COMMENT '开始时间',
    MODIFY COLUMN end_time DATETIME(3) DEFAULT NULL COMMENT '结束时间',
    MODIFY COLUMN duration_ms BIGINT DEFAULT NULL COMMENT '耗时毫秒',
    MODIFY COLUMN error_code VARCHAR(128) DEFAULT NULL COMMENT '错误码',
    MODIFY COLUMN error_message TEXT DEFAULT NULL COMMENT '错误信息',
    MODIFY COLUMN metadata JSON DEFAULT NULL COMMENT '扩展元数据',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE publish
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN resource_type VARCHAR(32) NOT NULL COMMENT '资源类型：AGENT/WORKFLOW 等',
    MODIFY COLUMN resource_id BIGINT UNSIGNED NOT NULL COMMENT '资源ID',
    MODIFY COLUMN version_id BIGINT UNSIGNED NOT NULL COMMENT '版本ID',
    MODIFY COLUMN channel VARCHAR(32) NOT NULL COMMENT '发布渠道：API/EMBED 等',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED' COMMENT '发布状态',
    MODIFY COLUMN published_by BIGINT UNSIGNED NOT NULL COMMENT '发布人用户ID',
    MODIFY COLUMN published_at DATETIME(3) NOT NULL COMMENT '发布时间',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE api_key
    COMMENT = '开放 API 密钥',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '密钥名称',
    MODIFY COLUMN key_prefix VARCHAR(32) NOT NULL COMMENT '密钥前缀（展示用）',
    MODIFY COLUMN key_hash VARCHAR(128) NOT NULL COMMENT '密钥哈希',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN expires_at DATETIME(3) DEFAULT NULL COMMENT '过期时间',
    MODIFY COLUMN last_used_at DATETIME(3) DEFAULT NULL COMMENT '最近使用时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE mcp_server
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '名称',
    MODIFY COLUMN server_key VARCHAR(128) NOT NULL COMMENT '服务唯一键',
    MODIFY COLUMN description VARCHAR(512) DEFAULT NULL COMMENT '描述',
    MODIFY COLUMN transport_type VARCHAR(32) NOT NULL DEFAULT 'SSE' COMMENT '传输类型：SSE 等',
    MODIFY COLUMN endpoint_url VARCHAR(1024) NOT NULL COMMENT '接入地址',
    MODIFY COLUMN auth_type VARCHAR(32) DEFAULT 'NONE' COMMENT '鉴权类型',
    MODIFY COLUMN auth_config JSON DEFAULT NULL COMMENT '鉴权配置',
    MODIFY COLUMN tool_catalog_json JSON DEFAULT NULL COMMENT '同步到的工具目录',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    MODIFY COLUMN last_sync_at DATETIME(3) DEFAULT NULL COMMENT '最近同步时间',
    MODIFY COLUMN created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE agent_mcp
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN version_id BIGINT UNSIGNED NOT NULL COMMENT '智能体版本ID',
    MODIFY COLUMN mcp_server_id BIGINT UNSIGNED NOT NULL COMMENT 'MCP 服务ID',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL COMMENT '创建时间';

ALTER TABLE agent_long_term_memory
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记忆ID',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '记忆内容',
    MODIFY COLUMN es_document_id VARCHAR(128) NOT NULL COMMENT 'Elasticsearch 文档ID',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';

ALTER TABLE tool_database_config
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tool_id BIGINT UNSIGNED NOT NULL COMMENT '工具ID',
    MODIFY COLUMN database_type VARCHAR(32) NOT NULL DEFAULT 'MYSQL' COMMENT '数据库类型',
    MODIFY COLUMN host VARCHAR(255) NOT NULL COMMENT '主机',
    MODIFY COLUMN port INT NOT NULL DEFAULT 3306 COMMENT '端口',
    MODIFY COLUMN database_name VARCHAR(128) NOT NULL COMMENT '库名',
    MODIFY COLUMN username VARCHAR(128) NOT NULL COMMENT '用户名',
    MODIFY COLUMN password_ciphertext TEXT NOT NULL COMMENT '加密密码',
    MODIFY COLUMN allowed_operations JSON DEFAULT NULL COMMENT '允许的操作',
    MODIFY COLUMN max_rows INT NOT NULL DEFAULT 100 COMMENT '最大返回行数',
    MODIFY COLUMN timeout_ms INT NOT NULL DEFAULT 10000 COMMENT '超时毫秒',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE tool_function_config
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN tool_id BIGINT UNSIGNED NOT NULL COMMENT '工具ID',
    MODIFY COLUMN function_name VARCHAR(128) NOT NULL COMMENT '函数名',
    MODIFY COLUMN function_code LONGTEXT NOT NULL COMMENT '函数代码',
    MODIFY COLUMN runtime VARCHAR(32) NOT NULL DEFAULT 'JAVA_SCRIPT' COMMENT '运行时',
    MODIFY COLUMN timeout_ms INT NOT NULL DEFAULT 5000 COMMENT '超时毫秒',
    MODIFY COLUMN memory_limit_mb INT NOT NULL DEFAULT 128 COMMENT '内存上限 MB',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE agent_sub_agent
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '主智能体ID',
    MODIFY COLUMN version_id BIGINT UNSIGNED NOT NULL COMMENT '主智能体版本ID',
    MODIFY COLUMN sub_agent_id BIGINT UNSIGNED NOT NULL COMMENT '子智能体ID',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

ALTER TABLE notification
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '通知ID',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '接收用户ID',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '标题',
    MODIFY COLUMN content VARCHAR(1024) NOT NULL COMMENT '内容',
    MODIFY COLUMN category VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' COMMENT '分类：SYSTEM 等',
    MODIFY COLUMN link_url VARCHAR(512) DEFAULT NULL COMMENT '跳转链接',
    MODIFY COLUMN read_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否已读：0未读 1已读',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE audit_log
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NULL COMMENT '工作空间ID',
    MODIFY COLUMN user_id BIGINT UNSIGNED NULL COMMENT '操作人用户ID',
    MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '操作动作',
    MODIFY COLUMN resource_type VARCHAR(32) NOT NULL COMMENT '资源类型',
    MODIFY COLUMN resource_id VARCHAR(64) NULL COMMENT '资源ID',
    MODIFY COLUMN resource_name VARCHAR(255) NULL COMMENT '资源名称',
    MODIFY COLUMN result VARCHAR(16) NOT NULL DEFAULT 'SUCCESS' COMMENT '结果：SUCCESS/FAIL',
    MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT '客户端 IP',
    MODIFY COLUMN trace_id VARCHAR(64) NULL COMMENT '链路追踪ID',
    MODIFY COLUMN detail VARCHAR(1024) NULL COMMENT '详情',
    MODIFY COLUMN created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间';

ALTER TABLE embed_custom_domain
    COMMENT = 'Embed 自定义域名',
    MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN workspace_id BIGINT UNSIGNED NOT NULL COMMENT '工作空间ID',
    MODIFY COLUMN agent_id BIGINT UNSIGNED NOT NULL COMMENT '智能体ID',
    MODIFY COLUMN domain VARCHAR(255) NOT NULL COMMENT '自定义域名',
    MODIFY COLUMN verify_token VARCHAR(64) NOT NULL COMMENT '域名验证令牌',
    MODIFY COLUMN verified TINYINT NOT NULL DEFAULT 0 COMMENT '是否已验证：0否 1是',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否 1是';
