export const PermissionCodes = {
  AGENT_CREATE: 'agent:create',
  AGENT_READ: 'agent:read',
  AGENT_UPDATE: 'agent:update',
  AGENT_DELETE: 'agent:delete',
  AGENT_PUBLISH: 'agent:publish',
  WORKFLOW_CREATE: 'workflow:create',
  WORKFLOW_READ: 'workflow:read',
  WORKFLOW_UPDATE: 'workflow:update',
  WORKFLOW_EXECUTE: 'workflow:execute',
  WORKFLOW_DELETE: 'workflow:delete',
  KNOWLEDGE_CREATE: 'knowledge:create',
  KNOWLEDGE_READ: 'knowledge:read',
  KNOWLEDGE_UPDATE: 'knowledge:update',
  KNOWLEDGE_UPLOAD: 'knowledge:upload',
  KNOWLEDGE_DELETE: 'knowledge:delete',
  TOOL_CREATE: 'tool:create',
  TOOL_UPDATE: 'tool:update',
  TOOL_DELETE: 'tool:delete',
  TOOL_EXECUTE: 'tool:execute',
  MODEL_CREATE: 'model:create',
  MODEL_UPDATE: 'model:update',
  MEMBER_MANAGE: 'member:manage',
  ROLE_MANAGE: 'role:manage',
  API_KEY_MANAGE: 'api_key:manage',
  AUDIT_READ: 'audit:read',
} as const

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes]
